name: merge-request
on:
  pull_request:
    branches: [ staging ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '19.5'
          cache: 'yarn'
      - name: Install packages
        run: yarn
      - name: Test build
        run: yarn build
